2025-07-16 04:05:30.086 | INFO     | uvicorn.server:_serve:84 - Started server process [96]
2025-07-16 04:05:30.086 | INFO     | uvicorn.lifespan.on:startup:48 - Waiting for application startup.
2025-07-16 04:05:30.102 | INFO     | uvicorn.lifespan.on:startup:62 - Application startup complete.
2025-07-16 04:05:30.102 | INFO     | uvicorn.server:_log_started_message:216 - Uvicorn running on http://0.0.0.0:12332 (Press CTRL+C to quit)
2025-07-16 04:05:30.222 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:35622 - "GET / HTTP/1.1" 200
2025-07-16 04:05:31.244 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:35634 - "GET / HTTP/1.1" 200
2025-07-16 04:05:32.259 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:35650 - "GET / HTTP/1.1" 200
2025-07-16 04:05:33.287 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:35654 - "GET / HTTP/1.1" 200
2025-07-16 04:05:33.141 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:38794 - "GET / HTTP/1.1" 200
2025-07-16 04:05:34.168 | INFO     | uvicorn.protocols.http.h11_impl:send:473 - 127.0.0.1:38806 - "GET / HTTP/1.1" 200
2025-07-16 04:05:34.264 | INFO     | uvicorn.server:shutdown:264 - Shutting down
2025-07-16 04:05:34.371 | INFO     | uvicorn.lifespan.on:shutdown:67 - Waiting for application shutdown.
2025-07-16 04:05:34.379 | ERROR    | uvicorn.lifespan.on:send:134 - Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 694, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 134, in merged_lifespan
    async with original_context(app) as maybe_original_state:
  File "/usr/local/lib/python3.11/contextlib.py", line 217, in __aexit__
    await anext(self.gen)
  File "/app/lean-server/LeanDockerWrapper/kimina-lean-server/server/server.py", line 99, in lifespan
    await task
  File "/app/lean-server/LeanDockerWrapper/kimina-lean-server/server/server.py", line 36, in _repl_creater
    repl = LeanREPL()
           ^^^^^^^^^^
  File "/app/lean-server/LeanDockerWrapper/kimina-lean-server/server/leanrepl.py", line 35, in __init__
    self.start_process()
  File "/app/lean-server/LeanDockerWrapper/kimina-lean-server/server/leanrepl.py", line 150, in start_process
    self.process = subprocess.Popen(
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/local/lib/python3.11/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'lake'

2025-07-16 04:05:34.379 | ERROR    | uvicorn.lifespan.on:shutdown:73 - Application shutdown failed. Exiting.
2025-07-16 04:05:34.380 | INFO     | uvicorn.server:_serve:94 - Finished server process [96]
